fail_fast: true

repos:
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
    language: python
    types: [python]
    entry: poetry run black --config pyproject.toml
